/* Autogenerated by varm NID generator. Do not edit manually. */
#pragma once

#include <stdint.h>

typedef struct {
    uint32_t nid;
    const char *func_name;
} V_NIDMap;

#define VARM_NID_COUNT 2

static const V_NIDMap varm_nid_table[VARM_NID_COUNT] = {
    { 0x1A2B3C4D, "sceSomethingSetState" },
    { 0x9ABCDEF0, "sceSomethingGetState" },
};
