import yaml
import os

# Paths configuration
yaml_path = "/home/gordon_freeman/Vita2Arm/Vita3K/external/vita-toolchain/yml_template/nid_db_classic.yml"
output_header_path = "/home/gordon_freeman/Vita2Arm/varm/include/varm_nids.h"

print("=== VARM NID CODE GENERATOR ===")
print(f"Reading database: {yaml_path}")

if not os.path.exists(yaml_path):
    print("[ERROR] Cannot find the NID database file!")
    exit(1)

with open(yaml_path, "r") as f:
    try:
        db = yaml.safe_load(f)
    except Exception as e:
        print(f"[ERROR] Failed to parse YAML: {e}")
        exit(1)

nid_mappings = []

# Dig into the modules structure
modules = db.get("modules", {})
for module_name, module_data in modules.items():
    libraries = module_data.get("libraries", {})
    for lib_name, lib_data in libraries.items():
        functions = lib_data.get("functions", {})
        if functions:
            for func_name, nid_val in functions.items():
                # Ensure the NID value is treated as an integer
                if isinstance(nid_val, str):
                    nid_uint = int(nid_val, 16)
                else:
                    nid_uint = nid_val
                
                nid_mappings.append((nid_uint, func_name))

# Sort everything by NID value so we can use blazing fast Binary Search later!
nid_mappings.sort(key=lambda x: x[0])

print(f"[SUCCESS] Extracted {len(nid_mappings)} system functions.")

# Write the high-performance C header file
os.makedirs(os.path.dirname(output_header_path), exist_ok=True)
with open(output_header_path, "w") as out:
    out.write("/* Autogenerated by varm NID generator. Do not edit manually. */\n")
    out.write("#pragma once\n\n")
    out.write("#include <stdint.h>\n\n")
    
    out.write("typedef struct {\n")
    out.write("    uint32_t nid;\n")
    out.write("    const char *func_name;\n")
    out.write("} V_NIDMap;\n\n")
    
    out.write(f"#define VARM_NID_COUNT {len(nid_mappings)}\n\n")
    out.write("static const V_NIDMap varm_nid_table[VARM_NID_COUNT] = {\n")
    
    for nid, name in nid_mappings:
        out.write(f"    {{ 0x{nid:08X}, \"{name}\" }},\n")
        
    out.write("};\n")

print(f"[SUCCESS] Generated static lookup table at: {output_header_path}")
